### ISSUE TITLE
Non S3 uploaded files return "Not Found"

### ISSUE THREAD

**Issue by SteffoSpieler** [hack13/Personal-Digital-Asset-Manager#1]
It seems like currently there is no way to get files that weren't uploaded using S3. (The route `/uploads/<filename>` doesn't exist.)

**Comment by hack13** [comment]
Can you provide information on your deployment? Are you using the container or building it yourself? If a container, how are you mapping the mount?

**Comment by SteffoSpieler** [comment]
I'm using the container image through my Synology NAS (using the latest release version of the container app).

My compose file looks like this:
```yml
services:
    pdam:
        image: git.hack13.dev/hack13/personal-digital-asset-manager:latest
        container_name: pdam
        restart: unless-stopped
        volumes:
            - /volume1/docker/pdam/uploads:/app/static/uploads
            - /volume1/docker/pdam/app.db:/app/instance/app.db
        ports:
            - 5876:5000

```
Since there's no example docker-compose file available, I had to guess many things. Please tell me if I missed anything.
