### ISSUE TITLE
Uploaded files don't get uploaded anymore

### ISSUE THREAD

**Issue by SteffoSpieler** [hack13/Personal-Digital-Asset-Manager#4]
Any file I try to upload doesn't get saved anymore.

My docker compose file:
```yaml
services:
    pdam:
        image: git.hack13.dev/hack13/personal-digital-asset-manager:latest
        container_name: pdam
        restart: unless-stopped
        volumes:
            - /volume1/docker/pdam/uploads:/app/static/uploads
            - /volume1/docker/pdam/app.db:/app/instance/app.db
        environment:
            - STORAGE_URL=file://static/uploads
        ports:
            - 5876:5000
```
